/**
 * All names declared here to be used within the VUEX files. If you wish to use these withing .vue files, please
 * refer to namedMutations.js file
 */
export default {
    AUTH_ERROR : 'AUTH_ERROR',
    AUTH_SET_TOKEN : 'AUTH_SET_TOKEN',
    AUTH_PROCESSING : 'AUTH_PROCESSING',

    BOOK_SET_DATA : 'SET_BOOKS',
    BOOK_PROCESSING : 'BOOKS_PROCESSING',
    BOOK_ERROR : 'BOOKS_ERROR',
    BOOK_SET_QUERY : 'SET_BOOK_QUERY',
    BOOK_NEW_PROCESSING: 'BOOK_NEW_PROCESSING',
    BOOK_NEW_ERROR: 'BOOK_NEW_ERROR',
    BOOK_UPDATE_PROCESSING : 'BOOK_UPDATE_PROCESSING',
    BOOK_UPDATE_ERROR : 'BOOK_UPDATE_ERROR',
    BOOK_DELETE_PROCESSING: 'BOOK_DELETE_PROCESSING',
    BOOK_DELETE_ERROR: 'BOOK_DELETE_ERROR',
    BOOK_NEW_SUCCESS: 'BOOK_NEW_SUCCESS',
    BOOK_UPDATE_SUCCESS: 'BOOK_UPDATE_SUCCESS',
    BOOK_DELETE_SUCCESS: 'BOOK_DELETE_SUCCESS',

    AUTHOR_SET_DATA : 'SET_AUTHORS',
    AUTHOR_FETCH_PROCESSING : 'AUTHOR_PROCESSING',
    AUTHOR_FETCH_ERROR: 'AUTHOR_ERROR',
    AUTHOR_NEW_ERROR : 'AUTHOR_NEW_ERROR',
    AUTHOR_NEW_PROCESSING: 'AUTHOR_NEW_PROCESSING',

    CATEGORY_SET_DATA : 'SET_CATEGORY',
    CATEGORY_FETCH_PROCESSING : 'CATEGORY_PROCESSING',
    CATEGORY_FETCH_ERROR: 'CATEGORY_ERROR',
    CATEGORY_NEW_ERROR: 'CATEGORY_NEW_ERROR',
    CATEGORY_NEW_PROCESSING: 'CATEGORY_NEW_PROCESSING',

    USERS_SET_DATA : 'SET_USERS',
    USERS_FETCH_PROCESSING: 'USERS_FETCH_PROCESSING',
    USERS_FETCH_ERROR: 'USERS_FETCH_ERROR',
    USERS_DELETE_PROCESSING: 'USERS_DELETE_PROCESSING',
    USERS_DELETE_ERROR: 'USERS_DELETE_ERROR',
    USERS_DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    USERS_EDIT_PROCESSING: 'USERS_EDIT_PROCESSING',
    USERS_EDIT_ERROR: 'USERS_EDIT_ERROR',
    USERS_EDIT_SUCCESS: 'USERS_EDIT_SUCCESS',
    USERS_ADD_PROCESSING : 'USERS_ADD_SUCCESS',
    USERS_ADD_ERROR: 'USERS_ADD_ERROR',
    USERS_ADD_SUCCESS: 'USERS_ADD_SUCCESS'
 }
